saving_paths:
  inference: "mixed_random_parallel/inference_random_mix.json"
  parsing: "mixed_random_parallel/full_prompt_parsed.json"
  results: "mixed_random_parallel/results_random_mix.json"

inference_configs:
  instruction: "You are a coding generation tool that will solve a problem using Python"
  model_path: "../models/llms/Llama-3.2-3B-Instruct"
  num_returns: 25
  num_generations: 200
  log_datetime: False
  quantization: True
  input_id: 4936
  context_ids: []
  context_type: "full_problem"
  evaluate_parallel: True

model_configs:
  temperature: 0.7
  top_p: 0.95
  max_length: 4098
  max_new_tokens: 1024

  