saving_paths:
  inference: "generations/inference_random_mix.json"
  parsing: "parsing/parsing_random_mix.json"
  results: "results/results_random_mix.json"

inference_configs:
  instruction: "You are a coding generation tool that will solve a problem using Python"
  model_path: "../models/llms/Llama-3.2-3B-Instruct"
  num_returns: 1
  num_generations: 1
  log_datetime: False
  quantization: True
  input_id: 
  context_ids: 

model_configs:
  temperature: 0.7
  top_p: 0.95
  max_length: 4098
  max_new_tokens: 1024

  