

inference_configs:
  instruction: "You are a coding generation tool that will solve a problem using Python"
  saving_path: "generations"
  model_path: "../models/llms/Llama-3.2-3B-Instruct"
  num_returns: 20
  num_generations: 20
  log_datetime: False
  quantization: True
  start_idx: 0
  end_idx: 120

model_configs:
  temperature: 0.7
  top_p: 0.95
  max_length: 2048

parse_config:
  saving_path: "parsed_generations"

results_config:
  saving_path: "results"
  log_only_total: True
  